export const categories = [
	{
		id: 1,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#00BFFF',
		placeholderBg: '#D3D8E4',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#00BFFF',
		mobile: false,
		tablet: false,
		desktop: true,
	},
	{
		id: 2,
		category: 'CATEGORY',
		categoryBg: '#00BFFF',
		image: '/src/assets/background.png',
		mobileBg: '#FF779A',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#00BFFF',
		mobile: false,
		tablet: false,
		desktop: true,
	},
	{
		id: 3,
		category: 'CATEGORY | DEVELOPMENT',
		categoryBg: '#081580',
		placeholderBg: '#FF779A',
		mobileBg: '#00BFFF',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#081580',
		mobile: false,
		tablet: false,
		desktop: true,
	},
	{
		id: 4,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#081580',
		placeholderBg: '#00B6DD',
		mobileBg: '#010101',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#081580',
		mobile: false,
		tablet: false,
		desktop: true,
	},
	{
		id: 5,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#00BFFF',
		image: '/src/assets/dark.webp',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#00BFFF',
		mobile: false,
		tablet: false,
		desktop: true,
	},
	{
		id: 6,
		category: 'CATEGORY',
		categoryBg: '#081580',
		placeholderBg: '#D3D8E4',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#081580',
		mobile: false,
		tablet: false,
		desktop: true,
	},

	{
		id: 7,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#00BFFF',
		placeholderBg: '#D3D8E4',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#00BFFF',
		desktop: false,
		mobile: false,
		tablet: true,
	},

	{
		id: 8,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#081580',
		placeholderBg: '#FF779A',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#081580',
		desktop: false,
		mobile: false,
		tablet: true,
	},

	{
		id: 9,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#081580',
		placeholderBg: '#00B6DD',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#081580',
		desktop: false,
		mobile: false,
		tablet: true,
	},

	{
		id: 10,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#00BFFF',
		placeholderBg: '#010101',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#00BFFF',
		desktop: false,
		mobile: false,
		tablet: true,
	},
	{
		id: 11,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#00BFFF',
		placeholderBg: '#D3D8E4',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#00BFFF',
		desktop: false,
		tablet: false,
		mobile: true,
	},
	{
		id: 12,
		category: 'CATEGORY | MARKETING',
		categoryBg: '#081580',
		placeholderBg: '#FF779A',
		title: 'Solutions for people like you',
		description:
			'How can we help your technology and services business develop a revenue engine based',
		buttonText: 'Call to action',
		buttonBg: '#081580',
		desktop: false,
		tablet: false,
		mobile: true,
	},
];
